- hosts: localhost
  become: yes
  tasks:
    - name: first task cluster connection 
      shell: gcloud container clusters get-credentials cluster-pv --zone us-east4-c --project jehad-iti

    - name: second task  namespace creation
      shell: kubectl create namespace jenkins

    - name: third task deploy jenkins & loadbalancer servies
      command: kubectl apply -f /home/jehad/test/jenkins/

