- hosts: localhost
  become: yes
  tasks:
    - name: Task -1 Connect to cluster
      shell: gcloud container clusters get-credentials priv-cluster --zone us-central1-c --project jehad-iti

    - name: Task -2 Create Jenkins namespace
      shell: kubectl create namespace jenkins

    - name: Task -3 Deploying jenkins & loadbalancer servies
      command: kubectl apply -f /home/jehad/test/jenkins/

